# Azure KeyVault Configuration
spring:
  cloud:
    azure:
      keyvault:
        uri: ${AZURE_KEYVAULT_URI}
        enabled: true
        secret:
          property-source-enabled: true
          property-sources:
            - endpoint: ${AZURE_KEYVAULT_URI}